[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
